"""update forum

Revision ID: 967ecbc45d5f
Revises: 97b05fa9ba85
Create Date: 2025-01-23 19:13:58.064292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967ecbc45d5f'
down_revision = '97b05fa9ba85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum', schema=None) as batch_op:
        batch_op.drop_constraint('forum_author_id_fkey', type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('forum_author_id_fkey', 'user_role', ['author_id'], ['id'])

    # ### end Alembic commands ###
